# Generated by Django 5.2.5 on 2025-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Obra')),
                ('categoria', models.CharField(choices=[('OLEO', 'Óleo sobre Tela'), ('ILUSTRACION', 'Ilustración Digital'), ('MURALISMO', 'Muralismo / Gran Formato')], default='OLEO', max_length=20, verbose_name='Línea de Arte')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible para Venta'), ('VENDIDO', 'Vendido'), ('COTI', 'Sólo Cotización')], default='DISPONIBLE', max_length=20, verbose_name='Estado de Venta')),
                ('imagen_url', models.URLField(max_length=500, verbose_name='URL Remota de la Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Obra de Arte',
                'verbose_name_plural': 'Obras de Arte',
                'ordering': ['-creado'],
            },
        ),
    ]
