# Generated by Django 5.2.5 on 2025-11-02 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Artista')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estilo/Técnica')),
            ],
            options={
                'verbose_name': 'Estilo o Etiqueta',
                'verbose_name_plural': 'Estilos y Etiquetas',
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='catalogo.artista', verbose_name='Artista Creador'),
        ),
        migrations.AddField(
            model_name='obra',
            name='estilos',
            field=models.ManyToManyField(related_name='obras_asociadas', to='catalogo.estilo', verbose_name='Estilos Aplicados'),
        ),
    ]
