# Generated by Django 5.2.5 on 2025-12-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_artista_estilo_obra_artista_obra_estilos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible para Venta"),
                    ("VENDIDO", "Vendido"),
                    ("COTI", "Sólo Cotización"),
                    ("ARCHIVADO", "Archivado"),
                ],
                default="DISPONIBLE",
                max_length=20,
                verbose_name="Estado de Venta",
            ),
        ),
    ]
