# Generated by Django 5.2.5 on 2025-12-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_alter_obra_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="año_exposicion",
            field=models.CharField(
                blank=True,
                help_text="Año en que se expuso esta obra (ej: 2023)",
                max_length=4,
                null=True,
                verbose_name="Año de Exposición",
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="mostrar_en_exposiciones",
            field=models.BooleanField(
                default=False,
                help_text="Máximo 6 obras pueden ser mostradas en exposiciones",
                verbose_name="Mostrar en Exposiciones Históricas",
            ),
        ),
    ]
