# Generated by Django 5.2.5 on 2025-12-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_obra_año_exposicion_obra_mostrar_en_exposiciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible para Venta"),
                    ("VENDIDO", "Vendido"),
                    ("COTI", "Sólo Cotización"),
                    ("EXPOSICION", "Exposición Histórica"),
                    ("ARCHIVADO", "Archivado"),
                ],
                default="DISPONIBLE",
                max_length=20,
                verbose_name="Estado de Venta",
            ),
        ),
    ]
