# Generated by Django 5.2.5 on 2025-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Banner Principal', max_length=100)),
                ('imagen', models.ImageField(upload_to='banners/', verbose_name='Imagen del Banner')),
            ],
            options={
                'verbose_name': 'Banner de Portada',
                'verbose_name_plural': 'Banner de Portada',
            },
        ),
    ]
