# Generated by Django 5.2.5 on 2025-10-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orden'], 'verbose_name': 'Slide de Banner', 'verbose_name_plural': 'Slides de Banner'},
        ),
        migrations.AddField(
            model_name='banner',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de aparición'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(default='Slide de Carrusel', max_length=100),
        ),
    ]
