# Generated by Django 5.2.5 on 2025-11-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='archivado',
            field=models.BooleanField(default=False, verbose_name='Archivado'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False, verbose_name='Respondido'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta del Admin'),
        ),
    ]
