# Generated by Django 5.2.5 on 2025-12-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contacto_archivado_contacto_fecha_respuesta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_sitio",
                    models.CharField(
                        default="Cristian Erre",
                        max_length=100,
                        verbose_name="Nombre del Sitio",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/",
                        verbose_name="Logo Navbar",
                    ),
                ),
                (
                    "logo_home",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/",
                        verbose_name="Logo Hero Home",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        default="Portfolio y Galería de arte",
                        verbose_name="Descripción Meta",
                    ),
                ),
                (
                    "email_contacto",
                    models.EmailField(
                        default="contacto@cristianerre.com",
                        max_length=254,
                        verbose_name="Email de Contacto",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración General",
                "verbose_name_plural": "Configuración General",
            },
        ),
        migrations.CreateModel(
            name="SeccionSitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        choices=[
                            ("hero_titulo", "Título Hero"),
                            ("hero_subtitulo", "Subtítulo Hero"),
                            ("bio_titulo", "Título Bio"),
                            ("bio_contenido", "Contenido Bio"),
                            ("servicios_titulo", "Título Servicios"),
                            ("servicios_descripcion", "Descripción Servicios"),
                            ("contacto_titulo", "Título Contacto"),
                            ("contacto_descripcion", "Descripción Contacto"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Clave de Sección",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título Mostrado"),
                ),
                ("contenido", models.TextField(verbose_name="Contenido")),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección del Sitio",
                "verbose_name_plural": "Secciones del Sitio",
                "ordering": ["orden"],
            },
        ),
    ]
