# Generated by Django 5.2.5 on 2025-12-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_configuraciongeneral_seccionsitio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfiguracionGeneral",
        ),
        migrations.DeleteModel(
            name="SeccionSitio",
        ),
        migrations.AddField(
            model_name="contacto",
            name="obra_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID de la obra consultada (si aplica)",
                null=True,
                verbose_name="ID de Obra",
            ),
        ),
        migrations.AddField(
            model_name="contacto",
            name="obra_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la obra consultada (si aplica)",
                max_length=200,
                verbose_name="Nombre de la Obra",
            ),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="asunto",
            field=models.CharField(
                choices=[
                    ("CONSULTA", "Consulta General"),
                    ("ENCARGO", "Encargo de Obra"),
                    ("MURAL", "Cotización de Muralismo"),
                    ("DISPONIBILIDAD", "Consultar Disponibilidad"),
                    ("COTIZACION", "Solicitar Cotización"),
                    ("OTRO", "Otro"),
                ],
                default="CONSULTA",
                max_length=20,
                verbose_name="Tipo de Consulta",
            ),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Correo Electrónico"),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="fecha_envio",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Envío"
            ),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AddIndex(
            model_name="contacto",
            index=models.Index(
                fields=["-fecha_envio"], name="core_contac_fecha_e_0ebfd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contacto",
            index=models.Index(
                fields=["obra_id"], name="core_contac_obra_id_d2a576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contacto",
            index=models.Index(fields=["asunto"], name="core_contac_asunto_41b04e_idx"),
        ),
    ]
