# Generated by Django 5.2.5 on 2025-12-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0002_artista_estilo_obra_artista_obra_estilos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_artista",
                    models.CharField(max_length=200, verbose_name="Nombre del Artista"),
                ),
                (
                    "bio_artista",
                    models.TextField(blank=True, verbose_name="Biografía (Opcional)"),
                ),
                (
                    "foto_artista_url",
                    models.URLField(
                        max_length=500, verbose_name="URL Foto del Artista"
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="DossierObra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden en el Dossier"
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dossier.dossier",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalogo.obra"
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
                "unique_together": {("dossier", "obra", "orden")},
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="obras",
            field=models.ManyToManyField(
                related_name="dossiers",
                through="dossier.DossierObra",
                to="catalogo.obra",
                verbose_name="Obras Seleccionadas",
            ),
        ),
    ]
